### ISSUE TITLE
FileController can't handle file name with Chinese character

### ISSUE THREAD

**Issue by videni** [symfony-cmf/media-bundle#150]
When I upload a file which has   Chinese character name, I can successfully upload the file , but it returns a wrong  url address to display.

**Comment by wangjiede** [comment]
I have also encountered this problem, return to the URL address: [/app_dev.php/media/image/cms/medias/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-12-19%2014.04.29.png_1457160688_82052323.png
![image](https://cloud.githubusercontent.com/assets/15643742/13546226/1efa11b0-e2e2-11e5-8b3e-06cc2d3e07e5.png)

**Comment by dbu** [comment]
this would mean there is a general encoding issue for higher range utf characters. now the reason could be in several different places. can you try to debug at which point the encoding breaks? is it when storing into PHPCR? or can the document still be retrieved but the name is invalid? or is it the Imagine bundle that ends up with an invalid path?

**Comment by videni** [comment]
to old, can be closed
