### ISSUE TITLE
Symfony 3.x compatibility

### ISSUE THREAD

**Issue by micronax** [symfony-cmf/media-bundle#153]

**Comment by dbu** [comment]
we currently lack resources to actively maintain the cmf media bundle, unfortunately. on a quick glance, it seems that the main suggested dependencies (cmf core bundle and liip imagine bundle) already support symfony 3. 

if you want to work on this, i am glad to provide assistance. the first step would be a pull request changing the build matrix in .travis.yml to include symfony 3 and change composer.json. then we see what is failing. 

from the [2.8 build](https://travis-ci.org/symfony-cmf/media-bundle/jobs/119807050) it looks like we have no deprecation warnings, which means it might simply work. on the other hand, the tests might not cover enough, there are not that many.

**Comment by ElectricMaxxx** [comment]
master is completely compatible with symfony 3.*
