### ISSUE TITLE
unimplemented getParent method

### ISSUE THREAD

**Issue by binhle410** [symfony-cmf/media-bundle#158]
the latest release of doctrine/phpcr-odm has removed method getParent so this has caused cmf/media-bundle to throw an exception:

```
Error: Class Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\File contains 1 abstract method and must therefore be declared abstract or implement the remaining methods 
(Symfony\Cmf\Bundle\MediaBundle\HierarchyInterface::getParent)
```

**Comment by dbu** [comment]
this does not install with phpcr-odm 2. https://github.com/symfony-cmf/media-bundle/blob/master/composer.json#L21

phpcr-odm 2.0 is not released yet, its a bit early to start adapting. but we will need to implement getParent in our models here for phpcr-odm 2, yes.
