### ISSUE TITLE
PHP Fatal error  Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Directory

### ISSUE THREAD

**Issue by h-sn** [symfony-cmf/media-bundle#165]
PHP Fatal error:  Class Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Directory contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Cmf\Bundle\MediaBundle\HierarchyInterface::getParent) in /var/www/contactlinza_beta/vendor/symfony-cmf/media-bundle/Doctrine/Phpcr/Directory.php on line 18

**Comment by dbu** [comment]
are you using phpcr-odm 2.0 (unstable)? version 1 was providing this method, but deprecated it.

i am fixing this in #166 but recommend you to use a stable release of phpcr-odm
