### ISSUE TITLE
Symfony\Cmf\Bundle\MediaBundle\Adapter\ElFinder\PhpcrDriver::$options must be protected or weaker

### ISSUE THREAD

**Issue by stefandoorn** [symfony-cmf/media-bundle#177]
```
FatalErrorException:
Compile Error: Access level to Symfony\Cmf\Bundle\MediaBundle\Adapter\ElFinder\PhpcrDriver::$options must be protected (as in class FM\ElFinderPHP\Driver\ElFinderVolumeDriver) or weaker
```

**Comment by dbu** [comment]
just a note: this bundle is currently not maintained, as stated in the readme. we don't have the capacity atm to maintain it, unfortunately.

**Comment by stefandoorn** [comment]
Ah, didn't see. Will see if I can submit a PR for this issue, will that be merged in that case?

**Comment by dbu** [comment]
i can hit merge, yes. but this has not been updated to recent php and symfony...

btw, if you want to take over maintenance, i am more than happy to give you commit rights on the repo.

**Comment by stefandoorn** [comment]
Hm ok, maybe not a good idea then to merge it, seems nobody is running into the issue anyway. I can't over maintenance, as I have no clue about the internals of this library, but thanks for the offer :) For now I'll make a fork to get around this issue.
